# language: pt
# encoding: utf-8

Funcionalidade: MINC_MAPAS_7.0_EPE02_010_Regras_de_Interface

  ---

  **COMO** usuário do sistema **MAPAS 7.0**

  **QUERO** definir as regras de interface

  **PARA** manter a integridade do sistema

  ---

  Cenário: 01. Listar Espaços
    Dado que o sistema esteja exibindo a **Lista de Espaços**
      | Campos             | Descrição                                        | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                                                                                          |
      | Título             | Nome do espaço                                   | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | ID                 | Identificador do espaço                          | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | TIPO               | Tipo do espaço                                   | Label            | Texto        | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Descrição          | Descrição curta sobre o espaço                   | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Endereço           | Endereço do espaço                               | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Acessibilidade     | Se espaço possui opções de acessibilidade        | Label            | Texto        | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Áreas de Interesse | Áreas de interesse relacionadas ao espaço        | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Tags               | Tags relacionadas ao espaço                      | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Título do espaço   | Nome do espaço para consulta                     | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Status do espaço   | Status em que se encontra o espaço para consulta | Checkbox         | Checkbox     | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Tipos de espaços   | Tipo do espaço para consulta                     | Seleção múltipla | Domínio Fixo | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Área de atuação    | Área de atuação do espaço para consulta          | Seleção múltipla | Domínio Fixo | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |

  Cenário: 02. Cadastrar Espaços
    Dado que o sistema esteja exibindo o **Formulário de Cadastro de Espaços**
      | Campos                                     | Descrição                  | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                                       | Nome do espaço             | Label            | Texto        | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Selecione o tipo do espaço                 | Tipo do espaço             | Seleção única    | Domínio Fixo | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Área de Atuação                            | Áreas de atuação do espaço | Seleção múltipla | Domínio fixo | -       | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Adicione uma Descrição curta para o Espaço | Descrição curta do espaço  | Label            | Texto        | 400     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |

  Cenário: 03. Visualizar Espaços
    Dado que o sistema esteja exibindo o **Formulário de Visualização de Espaços**
      | Campos                     | Descrição                                                      | Tipo do campo    | Tipo do dado | Tamanho | Máscara         | Hint | Editável | Obrigatório | Regras                                                                  |
      | Imagem de capa             | Imagem da capa do espaço                                       | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | -                                                                       |
      | Imagem de perfil           | Imagem do perfil do espaço                                     | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | -                                                                       |
      | Nome do espaço             | Título do espaço                                               | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | TIPO                       | Tipo do espaço                                                 | Seleção única    | Domínio fixo | N/A     | -               | -    | N        | -           | -                                                                       |
      | ID                         | Identificador do espaço                                        | Label            | Alfanumérico | N/A     | -               | -    | N        | -           | -                                                                       |
      | espaço INTEGRANTE DE       | Espaço macro do espaço atual                                   | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Descrição curta            | Descrição resumida do espaço                                   | Label            | Texto        | 400     | -               | -    | N        | -           | -                                                                       |
      | Link do espaço             | Endereço eletrônico de página web relacionada ao espaço        | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Horário                    | Horário de funcionamento do espaço                             | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Endereço                   | Endereço do espaço                                             | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-30](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/30) |
      | Recursos de acessibilidade | Opções de acessibilidade do espaço                             | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Capacidade do espaço       | Capacidade do espaço                                           | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Telefone(Público)          | Número de telefone que será exibido publicamente               | Label            | Númerico     | N/A     | (xx) xxxxx-xxxx | -    | N        | -           | -                                                                       |
      | E-mail(Público)            | Endereço de e-mail que será exibido publicamente               | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Descrição Detalhada        | Descrição detalhada do espaço                                  | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Arquivos para Download     | Arquivos disponibilizados para download relacionados ao espaço | Arquivo          | Arquivo      | 10mb    | -               | -    | N        | -           | -                                                                       |
      | Links                      | Links relevantes para o espaço                                 | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Galeria de vídeo           | Galeria de vídeos relevantes para o espaço                     | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Galeria de fotos           | Galeria de imagens relevantes para o espaço                    | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Tags                       | Tags relacionadas ao espaço                                    | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Instagram                  | Endereço de Instagram relacionado ao espaço                    | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Twitter/X                  | Endereço de Twitter/X relacionado ao espaço                    | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Facebook                   | Endereço de Facebook relacionado ao espaço                     | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Vimeo                      | Endereço de Vimeo relacionado ao espaço                        | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Youtube                    | Endereço de canal no Youtube relacionado ao espaço             | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Linkedin                   | Endereço de Linkedin relacionado ao espaço                     | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Spotify                    | Endereço de Spotify relacionado ao espaço                      | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Pinterest                  | Endereço de Pinterest relacionado ao espaço                    | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Publicado por              | Publicador do espaço                                           | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Administrado por           | Administradores do espaço                                      | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Supra Espaço                 | Supra Espaço cujo espaço atual seja um macro espaço              | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                       |
      | Verificações               | Certificações do espaço                                        | Seleção múltipla | Domínio fixo | N/A     | -               | -    | S        | -           | [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7)  |
      | Compartilhar               | Compartilhar espaço no twitter, facebook, whatsapp ou telegram | Seleção única    | Domínio fixo | N/A     | -               | -    | S        | -           |                                                                         |
      | Agentes Relacionados       | Apresenta agentes previamente inseridos no espaço              | Label            | Texto        | N/A     | -               | -    | S        | -           |                                                                         |
      | Áreas de Atuação           | Apresenta as áreas de atuação do espaço selecionado            | Label            | Texto        | N/A     | -               | -    | S        | -           |                                                                         |

  Cenário: 04. Denunciar Espaço
    Dado que o sistema esteja exibindo o **Formulário de Denúncia de Espaço**
      | Campos                           | Descrição                                                | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                             | Nome do denunciante                                      | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | E-mail                           | E-mail do denunciante                                    | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | Tipo                             | Tipo da denúncia                                         | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                         | Mensagem de detalhamento da denúncia                     | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar denúncia de forma anônima | Possibilidade de anonimato ao enviar a denúncia          | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem        | Possibilidade de receber uma cópia do e-mail de denúncia | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 05. Contato de Espaço
    Dado que o sistema esteja exibindo o **Formulário de Contato de Espaço**
      | Campos                             | Descrição                                                                     | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                               | Nome do remetente                                                             | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | E-mail                             | E-mail do remetente                                                           | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | Tipo                               | Tipo da mensagem                                                              | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                           | Mensagem de detalhamento do contato                                           | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar a mensagem de forma anônima | Possibilidade de anonimato ao enviar a mensagem                               | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem          | Possibilidade de receber uma cópia do e-mail de denúncia                      | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Enviar somente para o responsável  | Possibilidade de enviar a mensagem apenas para agente responsável pelo espaço | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 06. Editar Espaços
    Dado que o sistema esteja exibindo o **Formulário de Edição de Espaços**
      | Campos                             | Descrição                                                      | Tipo do campo    | Tipo do dado | Tamanho | Máscara         | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                    |
      | Imagem de capa                     | Imagem da capa do espaço                                       | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Imagem de perfil                   | Imagem do perfil do espaço                                     | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Nome do espaço                     | Título do espaço                                               | Label            | Texto        | N/A     | -               | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Tipo do espaço                     | Tipo do espaço                                                 | Seleção única    | Domínio fixo | N/A     | -               | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Descrição curta                    | Descrição resumida do espaço                                   | Label            | Texto        | 400     | -               | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Link para página ou site do espaço | Endereço eletrônico de página web relacionada ao espaço        | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | espaço vinculado à                 | espaço macro relacionado ao espaço atual                       | Seleção única    | Domínio fixo | -       | -               | -    | S        | N           | [RNG-21](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/21), [RNG-22](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/22)                                                                          |
      | Instagram                          | Endereço de Instagram relacionado ao espaço                    | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Twitter/X                          | Endereço de Twitter/X relacionado ao espaço                    | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Facebook                           | Endereço de Facebook relacionado ao espaço                     | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Vimeo                              | Endereço de Vimeo relacionado ao espaço                        | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Youtube                            | Endereço de canal no Youtube relacionado ao espaço             | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Linkedin                           | Endereço de Linkedin relacionado ao espaço                     | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Spotify                            | Endereço de Spotify relacionado ao espaço                      | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Pinterest                          | Endereço de Pinterest relacionado ao espaço                    | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | CEP                                | CEP do espaço                                                  | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-29](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/29)                                                                                                                                                   |
      | Logradouro                         | Logradouro do espaço                                           | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Número                             | Número de endereço do espaço                                   | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Bairro                             | Bairro do espaço                                               | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Complemento ou ponto de referência | COmplemento do endereço do espaço                              | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Estado                             | Estado de localização do espaço                                | Seleção única    | Domínio fixo | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Município                          | Município de localização do espaço                             | Seleção única    | Domínio fixo | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Acessibilidade                     | Se o espaço possui opções de acessibilidade                    | Seleção única    | Domínio fixo | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Acessibilidade física              | Quais opções de acessibilidade o espaço possui                 | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Capacidade                         | Capacidade total do espaço em número de pessoas                | Numérico         | Numérico     | -       | -               | -    | S        | N           | [RNG-35](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/35) e [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                         |
      | Horário e funcionamento            | Horário de funcionamento do espaço                             | Alfanumérico     | Texto        | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | E-mail Público                     | Endereço de e-mail que será exibido publicamente               | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-15](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/15), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | E-mail Privado                     | Endereço de e-mail privado, que não será exibido publicamente  | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-15](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/15), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone Público                   | Número de telefone que será exibido publicamente               | Label            | Númerico     | N/A     | (xx) xxxxx-xxxx | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone privado 1                 | Número de telefone privado, que não será exibido publicamente  | Label            | Númerico     | N/A     | (xx) xxxxx-xxxx | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone privado 2                 | Número de telefone privado, que não será exibido publicamente  | Label            | Númerico     | N/A     | (xx) xxxxx-xxxx | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Descrição                          | Descrição detalhada do espaço                                  | Label            | Texto        | N/A     | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Adicionar arquivo para download    | Arquivos disponibilizados para download relacionados ao espaço | Arquivo          | Arquivo      | 10mb    | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-18](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/18), [RNG-19](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/19) |
      | Adicionar links                    | Links relevantes para o espaço                                 | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Adicionar vídeos                   | Galeria de vídeos relevantes para o espaço                     | URL              | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Adicionar fotos na galeria         | Galeria de imagens relevantes para o espaço                    | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Áreas de atuação                   | Áreas de atuação relacionadas ao espaço                        | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Nome do agente                     | Nome de agente relacionado como administrador do espaço        | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-23](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/23)                                                                          |
      | Nome da Tag                        | Tags relacionadas ao espaço                                    | Seleção múltipla | Texto        | N/A     | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do Grupo                      | Grupos relacionados ao espaço                                  | Seleção múltipla | Texto        | N/A     | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do agente                     | Nome de agente relacionado como publicador do espaço           | Seleção única    | Domínio fixo | -       | -               | -    | S        | S           | [RNG-24](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/24)                                                                                                                                                   |
      | Permissões                         | Permissões do cadastro do espaço                               | Seleção única    | Domínio fixo | -       | -               | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Publicado por                      | Informa o responsável pela publicação                          | Label            | Texto        | -       | -               | -    | N       | N           | -                                                                                                                                                                                                                         |
      | Adicionar Supra Espaço             | Vincula o seu espaço a outro espaço                            | Seleção única    | Texto        | -       | -               |-     | N       | N           | -                                                                                                                                                                                                                         |

  Cenário: 07. Meus Espaços
    Dado que o sistema esteja exibindo a **Lista de Espaços Pessoais**
      | Campos         | Descrição                                  | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                            |
      | Título         | Nome do espaço                             | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
      | TIPO           | Tipo do espaço                             | Label         | Texto        | -       | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
      | Palavras-chave | Palavra que faça parte do título do espaço | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
