# language: pt
# encoding: utf-8

Funcionalidade: MINC_MAPAS_7.0_EPE04_010_Regras_de_Interface

  ---

  **COMO** usuário do sistema **MAPAS 7.0**

  **QUERO** definir as regras de interface

  **PARA** manter a integridade do sistema

  ---

  Cenário: 01. Listar Oportunidades
    Dado que o sistema esteja exibindo a **Lista de Oportunidades**
      | Campos                | Descrição                                      | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                                                                                          |
      | Título                | Nome da oportunidade                           | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | ID                    | Identificador do oportunidade                  | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | TIPO                  | Tipo da oportunidade                           | Label         | Texto        | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Descrição             | Descrição curta sobre a oportunidade           | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Status das inscrições | Situação do período de inscrições              | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Período de instrição  | Datas inicial e final do período de instrição  | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Áreas de Interesse    | Áreas de interesse relacionadas à oportunidade | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Tags                  | Tags relacionadas à oportunidade               | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Selos                 | Verificações e certificados da oportunidade    | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |

  Cenário: 02. Cadastrar Oportunidades
    Dado que o sistema esteja exibindo o **Formulário de Cadastro de Oportunidades**
      | Campos                                | Descrição                              | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Título                                | Nome da oportunidade                   | Label            | Texto        | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Selecione o tipo da oportunidade      | Tipo da oportunidade                   | Seleção única    | Domínio Fixo | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Área de Interesse                     | Áreas de interesse da oportunidade     | Seleção múltipla | Domínio fixo | -       | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Vincule a oportunidade a uma entidade | Vínculo da oportunidade a uma entidade | Seleção única    | Domínio fixo | -       | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |

  Cenário: 03. Visualizar Oportunidades
    Dado que o sistema esteja exibindo o **Formulário de Visualização de Oportunidades**
      | Campos                 | Descrição                                                           | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                 |
      | Imagem de capa         | Imagem da capa da oportunidade                                      | Arquivo          | Arquivo      | N/A     | -       | -    | S        | -           | -                                                                      |
      | Imagem de perfil       | Imagem do perfil da oportunidade                                    | Arquivo          | Arquivo      | N/A     | -       | -    | N        | -           | -                                                                      |
      | Título                 | Título da oportunidade                                              | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                      |
      | TIPO                   | Tipo da oportunidade                                                | Seleção única    | Domínio fixo | N/A     | -       | -    | N        | -           | -                                                                      |
      | ID                     | Identificador da oportunidade                                       | Label            | Alfanumérico | N/A     | -       | -    | N        | -           | -                                                                      |
      | Descrição curta        | Descrição resumida do oportunidade                                  | Label            | Texto        | 400     | -       | -    | N        | -           | -                                                                      |
      | Arquivos para Download | Arquivos disponibilizados para download relacionados à oportunidade | Arquivo          | Arquivo      | 10mb    | -       | -    | N        | -           | -                                                                      |
      | Links                  | Links relevantes para a oportunidade                                | Label            | Texto        | N/A     | -       | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Galeria de vídeo       | Galeria de vídeos relevantes para a oportunidade                    | Arquivo          | Arquivo      | N/A     | -       | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6) |
      | Galeria de fotos       | Galeria de imagens relevantes para a oportunidade                   | Arquivo          | Arquivo      | N/A     | -       | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6) |
      | Tags                   | Tags relacionadas à oportunidade                                    | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                      |
      | Instagram              | Endereço de Instagram relacionado à oportunidade                    | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Twitter/X              | Endereço de Twitter/X relacionado à oportunidade                    | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Facebook               | Endereço de Facebook relacionado à oportunidade                     | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Vimeo                  | Endereço de Vimeo relacionado à oportunidade                        | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Youtube                | Endereço de canal no Youtube relacionado à oportunidade             | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Linkedin               | Endereço de Linkedin relacionado à oportunidade                     | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Spotify                | Endereço de Spotify relacionado à oportunidade                      | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Pinterest              | Endereço de Pinterest relacionado à oportunidade                    | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Publicado por          | Publicador da oportunidade                                          | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                      |
      | Administrado por       | Administradores d oportunidade                                      | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                      |
      | Verificações           | Certificações da oportunidade                                       | Seleção múltipla | Domínio fixo | N/A     | -       | -    | S        | -           | [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7) |

  Cenário: 04. Denunciar Oportunidade
    Dado que o sistema esteja exibindo o **Formulário de Denúncia de Oportunidade**
      | Campos                           | Descrição                                                | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                             | Nome do denunciante                                      | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | E-mail                           | E-mail do denunciante                                    | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | Tipo                             | Tipo da denúncia                                         | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                         | Mensagem de detalhamento da denúncia                     | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar denúncia de forma anônima | Possibilidade de anonimato ao enviar a denúncia          | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem        | Possibilidade de receber uma cópia do e-mail de denúncia | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 05. Contato de Oportunidade
    Dado que o sistema esteja exibindo o **Formulário de Contato de Oportunidade**
      | Campos                             | Descrição                                                                           | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                               | Nome do remetente                                                                   | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | E-mail                             | E-mail do remetente                                                                 | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | Tipo                               | Tipo da mensagem                                                                    | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                           | Mensagem de detalhamento do contato                                                 | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar a mensagem de forma anônima | Possibilidade de anonimato ao enviar a mensagem                                     | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem          | Possibilidade de receber uma cópia do e-mail de denúncia                            | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Enviar somente para o responsável  | Possibilidade de enviar a mensagem apenas para agente responsável pelo oportunidade | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 06. Gerenciar Oportunidades
    Dado que o sistema esteja exibindo o **Formulário de Gerenciamento de Oportunidades**
      | Campos                                       | Descrição                                                           | Tipo do campo    | Tipo do dado | Tamanho | Máscara          | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                    |
      | Imagem de capa                               | Imagem da capa da oportunidade                                      | Arquivo          | Arquivo      | N/A     | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Imagem de perfil                             | Imagem do perfil da oportunidade                                    | Arquivo          | Arquivo      | N/A     | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Título                                       | Título da oportunidade                                              | Label            | Texto        | N/A     | -                | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Selecione o tipo da oportunidade             | Tipo da oportunidade                                                | Seleção única    | Domínio fixo | N/A     | -                | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Descrição curta                              | Descrição resumida da oportunidade                                  | Label            | Texto        | 400     | -                | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Data de início das inscrições                | Data de início das inscrições na oportunidade                       | Data e hora      | Data e hora  | -       | DD/MM/AAAA HH:MM | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Data final das inscrições                    | Data de fim das inscrições na oportunidade                          | Data e hora      | Data e hora  | -       | DD/MM/AAAA HH:MM | -    | S        | S           | [RNG-21](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/21), [RNG-22](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/22)                                                                          |
      | Publicação final de resultados (data e hora) | Data de publicação de resultados                                    | Data de hora     | Data e hora  | -       | DD/MM/AAAA HH:MM | -    | S        | N           | [RNG-29](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/29)                                                                                                                                                   |
      | Entidade vinculada                           | Nome da entidade vinculada à oportunidade                           | Seleção única    | Domínio fixo | -       | -                | -    | S        | S           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Adicionar regulamento                        | Arquivo de regulamento da oportunidade                              | Arquivo          | Arquivo      | 10Mb    | -                | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Instagram                                    | Endereço de Instagram relacionado à oportunidade                    | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Twitter/X                                    | Endereço de Twitter/X relacionado à oportunidade                    | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Facebook                                     | Endereço de Facebook relacionado à oportunidade                     | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Vimeo                                        | Endereço de Vimeo relacionado à oportunidade                        | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Youtube                                      | Endereço de canal no Youtube relacionado à oportunidade             | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Linkedin                                     | Endereço de Linkedin relacionado à oportunidade                     | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Spotify                                      | Endereço de Spotify relacionado à oportunidade                      | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Pinterest                                    | Endereço de Pinterest relacionado à oportunidade                    | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Adicionar arquivo para download              | Arquivos disponibilizados para download relacionados à oportunidade | Arquivo          | Arquivo      | 10mb    | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-18](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/18), [RNG-19](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/19) |
      | Adicionar links                              | Links relevantes para a oportunidade                                | Label            | Texto        | N/A     | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Adicionar vídeos                             | Galeria de vídeos relevantes para a oportunidade                    | Arquivo          | Arquivo      | N/A     | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Adicionar fotos na galeria                   | Galeria de imagens relevantes para a oportunidade                   | Arquivo          | Arquivo      | N/A     | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Áreas de interesse                           | Áreas de interesse relacionadas à oportunidade                      | Seleção múltipla | Domínio fixo | -       | -                | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Nome do agente Administrador                 | Nome de agente relacionado como administrador da oportunidade       | Seleção múltipla | Domínio fixo | -       | -                | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-23](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/23)                                                                          |
      | Nome da Tag                                  | Tags relacionadas à oportunidade                                    | Seleção múltipla | Texto        | N/A     | -                | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do Grupo                                | Grupos relacionados à oportunidade                                  | Seleção múltipla | Texto        | N/A     | -                | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do agente Publicador                    | Nome de agente relacionado como publicador da oportunidade          | Seleção única    | Domínio fixo | -       | -                | -    | S        | S           | [RNG-24](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/24)                                                                                                                                                   |
      | Verificações                                 | Certificações da oportunidade                                       | Seleção múltipla | Domínio fixo | -       | -                | -    | S        | N           | [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7)                                                                                                                                                    |

  Cenário: 07. Minhas Oportunidades
    Dado que o sistema esteja exibindo a **Lista de Oportunidades Pessoais**
      | Campos         | Descrição                                        | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                            |
      | Título         | Nome da oportunidade                             | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
      | TIPO           | Tipo da oportunidade                             | Label         | Texto        | -       | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
      | Palavras-chave | Palavra que faça parte do título da oportunidade | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
