# language: pt
# encoding: utf-8

Funcionalidade: MINC_MAPAS_7.0_EPE05_010_Regras_de_Interface

  ---

  **COMO** usuário do sistema **MAPAS 7.0**

  **QUERO** definir as regras de interface

  **PARA** manter a integridade do sistema

  ---

  Cenário: 01. Listar Agentes
    Dado que o sistema esteja exibindo a **Lista de Agentes**
      | Campos                    | Descrição                                        | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                                                                                          |
      | Nome                      | Nome do agente                                   | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | ID                        | Identificador do agente                          | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Este agente atua de forma | Tipo do agente                                   | Label            | Texto        | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Descrição                 | Descrição curta sobre o agente                   | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Áreas de Interesse        | Áreas de interesse relacionadas ao agente        | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Tags                      | Tags relacionadas ao agente                      | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Título do agente          | Nome do agente para consulta                     | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Status do agente          | Status em que se encontra o agente para consulta | Checkbox         | Checkbox     | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Tipo                      | Tipo do agente para consulta                     | Seleção múltipla | Domínio Fixo | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Área de atuação           | Área de atuação do agente para consulta          | Seleção múltipla | Domínio Fixo | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |

  Cenário: 02. Cadastrar Agentes
    Dado que o sistema esteja exibindo o **Formulário de Cadastro de Agentes**
      | Campos                                     | Descrição                  | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                                       | Nome do agente             | Label            | Texto        | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Selecione o tipo do agente                 | Tipo do agente             | Seleção única    | Domínio Fixo | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Área de Atuação                            | Áreas de atuação do agente | Seleção múltipla | Domínio fixo | -       | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Adicione uma Descrição curta para o Agente | Descrição curta do agente  | Label            | Texto        | 400     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |

  Cenário: 03. Visualizar Agentes
    Dado que o sistema esteja exibindo o **Formulário de Visualização de Agentes**
      | Campos                  | Descrição                                                      | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Imagem de capa          | Imagem da capa do agente                                       | Arquivo          | Arquivo      | N/A     | -       | -    | S        | -           | -                                                                       |
      | Imagem de perfil        | Imagem do perfil do agente                                     | Arquivo          | Arquivo      | N/A     | -       | -    | N        | -           | -                                                                       |
      | Nome do agente          | Título do agente                                               | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                       |
      | TIPO                    | Tipo do agente                                                 | Seleção única    | Domínio fixo | N/A     | -       | -    | N        | -           | -                                                                       |
      | ID                      | Identificador do agente                                        | Label            | Alfanumérico | N/A     | -       | -    | N        | -           | -                                                                       |
      | Descrição curta         | Descrição resumida do agente                                   | Label            | Texto        | 400     | -       | -    | N        | -           | -                                                                       |
      | Endereço                | Endereço do agente                                             | Label            | Texto        | N/A     | -       | -    | N        | -           | [RNG-30](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/30) |
      | Email pessoal           | Endereço de e-mail que será exibido publicamente               | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                       |
      | Descrição Detalhada     | Descrição detalhada do agente                                  | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                       |
      | Arquivos para Download  | Arquivos disponibilizados para download relacionados ao agente | Arquivo          | Arquivo      | 10mb    | -       | -    | N        | -           | -                                                                       |
      | Links                   | Links relevantes para o agente                                 | Label            | Texto        | N/A     | -       | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Galeria de vídeo        | Galeria de vídeos relevantes para o agente                     | Arquivo          | Arquivo      | N/A     | -       | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Galeria de fotos        | Galeria de imagens relevantes para o agente                    | Arquivo          | Arquivo      | N/A     | -       | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Tags                    | Tags relacionadas ao agente                                    | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                       |
      | Redes Sociais Instagram | Endereço de Instagram relacionado ao agente                    | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Twitter/X | Endereço de Twitter/X relacionado ao agente                    | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Facebook  | Endereço de Facebook relacionado ao agente                     | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Vimeo     | Endereço de Vimeo relacionado ao agente                        | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Youtube   | Endereço de canal no Youtube relacionado ao agente             | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Linkedin  | Endereço de Linkedin relacionado ao agente                     | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Spotify   | Endereço de Spotify relacionado ao agente                      | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Redes Sociais Pinterest | Endereço de Pinterest relacionado ao agente                    | Label            | Texto        | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Publicado por           | Publicador do agente                                           | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                       |
      | Administrado por        | Administradores do agente                                      | Label            | Texto        | N/A     | -       | -    | N        | -           | -                                                                       |
      | Função                  | Função do agente na cultura                                    | Seleção múltipla | Domínio fixo | N/A     | -       | -    | N        | -           | -                                                                       |
      | Verificações            | Certificações do agente                                        | Seleção múltipla | Domínio fixo | N/A     | -       | -    | S        | -           | [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7)  |
      | Compartilhar Twitter/X  | Compartilhar na rede social Twitter                            | Seleção          | Imagem       | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Compartilhar Facebook   | Compartilhar na rede social Facebook                           | Seleção          | Imagem       | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Compartilhar Whatsapp   | Compartilhar na rede social Whatsapp                           | Seleção          | Imagem       | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Compartilhar Telegram   | Compartilhar na rede social Telegram                           | Seleção          | Imagem       | N/A     | -       | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |

  Cenário: 04. Denunciar Agente
    Dado que o sistema esteja exibindo o **Formulário de Denúncia de Agente**
      | Campos                           | Descrição                                                | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                             | Nome do denunciante                                      | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | E-mail                           | E-mail do denunciante                                    | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | Tipo                             | Tipo da denúncia                                         | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                         | Mensagem de detalhamento da denúncia                     | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar denúncia de forma anônima | Possibilidade de anonimato ao enviar a denúncia          | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem        | Possibilidade de receber uma cópia do e-mail de denúncia | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 05. Contato de Agente
    Dado que o sistema esteja exibindo o **Formulário de Contato de Agente**
      | Campos                             | Descrição                                                                     | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                               | Nome do remetente                                                             | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | E-mail                             | E-mail do remetente                                                           | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | Tipo                               | Tipo da mensagem                                                              | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                           | Mensagem de detalhamento do contato                                           | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar a mensagem de forma anônima | Possibilidade de anonimato ao enviar a mensagem                               | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem          | Possibilidade de receber uma cópia do e-mail de denúncia                      | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Enviar somente para o responsável  | Possibilidade de enviar a mensagem apenas para agente responsável pelo agente | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 06. Editar Agentes
    Dado que o sistema esteja exibindo o **Formulário de Edição de Agentes**
      | Campos                             | Descrição                                                      | Tipo do campo    | Tipo do dado | Tamanho | Máscara         | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                    |
      | Imagem de capa                     | Imagem da capa do agente                                       | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Imagem de perfil                   | Imagem do perfil do agente                                     | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Nome do agente                     | Título do agente                                               | Label            | Texto        | N/A     | -               | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Descrição curta                    | Descrição resumida do agente                                   | Label            | Texto        | 400     | -               | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Instagram                          | Endereço de Instagram relacionado ao agente                    | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Twitter/X                          | Endereço de Twitter/X relacionado ao agente                    | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Facebook                           | Endereço de Facebook relacionado ao agente                     | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Vimeo                              | Endereço de Vimeo relacionado ao agente                        | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Youtube                            | Endereço de canal no Youtube relacionado ao agente             | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Linkedin                           | Endereço de Linkedin relacionado ao agente                     | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Spotify                            | Endereço de Spotify relacionado ao agente                      | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Pinterest                          | Endereço de Pinterest relacionado ao agente                    | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | CEP                                | CEP do agente                                                  | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-29](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/29)                                                                                                                                                   |
      | Logradouro                         | Logradouro do agente                                           | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Número                             | Número de endereço do agente                                   | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Bairro                             | Bairro do agente                                               | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Complemento ou ponto de referência | COmplemento do endereço do agente                              | Alfanumérico     | Texto        | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Estado                             | Estado de localização do agente                                | Seleção única    | Domínio fixo | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Município                          | Município de localização do agente                             | Seleção única    | Domínio fixo | N/A     | -               | -    | S        | N           | [RNG-34](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/34)                                                                                                                                                   |
      | Acessibilidade                     | Se o agente possui opções de acessibilidade                    | Seleção única    | Domínio fixo | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Acessibilidade física              | Quais opções de acessibilidade o agente possui                 | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Capacidade                         | Capacidade total do agente em número de pessoas                | Numérico         | Numérico     | -       | -               | -    | S        | N           | [RNG-35](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/35) e [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                         |
      | Horário e funcionamento            | Horário de funcionamento do agente                             | Alfanumérico     | Texto        | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | E-mail Público                     | Endereço de e-mail que será exibido publicamente               | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-15](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/15), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | E-mail Privado                     | Endereço de e-mail privado, que não será exibido publicamente  | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-15](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/15), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone Público                   | Número de telefone que será exibido publicamente               | Label            | Texto        | N/A     | (xx) xxxxx-xxxx | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone privado 1                 | Número de telefone privado, que não será exibido publicamente  | Label            | Texto        | N/A     | (xx) xxxxx-xxxx | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone privado 2                 | Número de telefone privado, que não será exibido publicamente  | Label            | Texto        | N/A     | (xx) xxxxx-xxxx | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Descrição                          | Descrição detalhada do agente                                  | Label            | Texto        | N/A     | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Adicionar arquivo para download    | Arquivos disponibilizados para download relacionados ao agente | Arquivo          | Arquivo      | 10mb    | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-18](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/18), [RNG-19](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/19) |
      | Adicionar links                    | Links relevantes para o agente                                 | Label            | Texto        | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Adicionar vídeos                   | Galeria de vídeos relevantes para o agente                     | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Adicionar fotos na galeria         | Galeria de imagens relevantes para o agente                    | Arquivo          | Arquivo      | N/A     | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Áreas de atuação                   | Áreas de atuação relacionadas ao agente                        | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Nome do agente                     | Nome de agente relacionado como administrador do agente        | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-23](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/23)                                                                          |
      | Nome da Tag                        | Tags relacionadas ao agente                                    | Seleção múltipla | Texto        | N/A     | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do Grupo                      | Grupos relacionados ao agente                                  | Seleção múltipla | Texto        | N/A     | -               | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do agente                     | Nome de agente relacionado como publicador do agente           | Seleção única    | Domínio fixo | -       | -               | -    | S        | S           | [RNG-24](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/24)                                                                                                                                                   |
      | Função na cultura                  | Função do agente na cultura                                    | Seleção múltipla | Domínio fixo | -       | -               | -    | S        | N           | -                                                                                                                                                                                                                         |

  Cenário: 07. Meus Agentes
    Dado que o sistema esteja exibindo a **Lista de Agentes Pessoais**
      | Campos         | Descrição                                  | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                            |
      | Título         | Nome do agente                             | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
      | TIPO           | Tipo do agente                             | Label         | Texto        | -       | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
      | Palavras-chave | Palavra que faça parte do título do agente | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-43](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/43) |
