#enconding: utf-8
#language: pt

Funcionalidade: MINC_MAPAS_7.0_EPE01_003_Visualizar

  ---
  **COMO** usuário do sistema **MAPAS 7.0** conforme a [RNG-01](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/1)

  **QUERO** acessar a funcionalidade **Visualizar Projeto**

  **PARA** visualizar as informações do projeto no sistema

  ---

  Contexto: Critérios de Aceitação
    Dado que o usuário acesse a opção **Projetos**
    E o sistema exibe a **Lista de Projetos** conforme as [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9)
      | Título                      | ID | Tipo       | Descrição                                                                                                                                  |
      | Programa Cultura Viva       | 6  | Inscrições | A Cultura Viva é uma política pública cultural voltada para o reconhecimento e apoio às atividades e processos culturais já desenvolvidos. |
      | O Circo Chegou!             | 5  | Festival   | O objetivo geral é difundir a arte circense por um meio de espetáculos e interação com artistas circenses e o público.                     |
      | Histórias da Nossa História | 4  | Exibição   | A proposta é manter viva as manifestações culturais, brincadeiras populares e resgatar o folclore nacional.                                |
      | Segundo Volume              | 3  | Oficina    | Com a intenção de responder à necessidade atual de material impresso voltado à arte, música e literatura.                                  |
      | PETS                        | 2  | Feira      | Realizar duas feiras do livro com o tema PETS com distribuição gratuita de livros onde os personagens são cães e gatos                     |
      | Cachinhos Dourados          | 1  | Sarau      | Promover o acesso a espetáculo infantil de qualidade artística superior para crianças em situação de vulnerabilidade social.               |
    E apresenta os <Campos> para **filtragem** dos registros
      | Campos            |
      | Título do projeto |
      | Status do projeto |
      | Tipos de projetos |
    Quando o usuário aciona a opção **Acessar** em algum projeto
    Então o sistema  apresenta o formulário de visualização do Projeto selecionado com os <Campos> **desabilitados** para edição conforme [RNG-39](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/39)
      | Campos                                |
      | **Cabeçalho**                         |
      | Imagem de capa                        |
      | Imagem de perfil                      |
      | Nome do Projeto                       |
      | ID                                    |
      | TIPO                                  |
      | PROJETO INTEGRANTE DE                 |
      | Descrição curta                       |
      | Link do Projeto                       |
      | **Lista de oportunidades vinculadas** |
      | Nome da Oportunidade                  |
      | **Informações adicionais**            |
      | Telefone (Público)                    |
      | E-mail (Público)                      |
      | **Descrição Detalhada**               |
      | **Arquivos para Download**            |
      | **Links**                             |
      | **Galeria de vídeo**                  |
      | **Galeria de fotos**                  |
      | **Tags**                              |
      | Instagram                             |
      | Twitter/X                             |
      | Facebook                              |
      | Vimeo                                 |
      | Youtube                               |
      | Linkedin                              |
      | Spotify                               |
      | Pinterest                             |
      | **Publicado por**                     |
      | **Administrado por**                  |
      | **Subprojetos**                       |
    E os <Campos> **habilitados** para edição
      | Campos           |
      | **Verificações** |

  Cenário: 01. Visualizar Projeto
    Quando o usuário aciona a opção **Acessar** em um projeto
    Então o sistema apresenta os seguintes <Campos> do registro selecionado
      | Campos                                | Exemplos                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | **Cabeçalho**                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Nome do Projeto                       | Histórias da Nossa História                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | ID                                    | 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | TIPO                                  | Exibição                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | PROJETO INTEGRANTE DE                 | Projeto Cultura Viva                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Descrição curta                       | A proposta é manter viva as manifestações culturais, brincadeiras populares e resgatar o folclore nacional.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | Link do Projeto                       | https://bancodeprojetosaprovados.campinas.sp.gov.br/projetos_proac/historias-da-nossa-historia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | **Lista de oportunidades vinculadas** |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Nome da Oportunidade                  | Certificação como Ponto ou Pontão de Cultura                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | **Informações adicionais**            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Telefone (Público)                    | (61) 99999-9999                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | E-mail (Público)                      | historiasdanossahistoria@gmail.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | **Descrição Detalhada**               | Circulação da peça teatral infantil “O QUE SERÁ?” em dez cidades do Estado de São Paulo. Serão ao todo 20 apresentações (duas apresentações em cada cidade), levando para as cidades escolhidas temáticas de folclore, brincadeiras populares e cultura popular. Como contrapartida à população, os ingressos serão totalmente gratuitos e será realizada uma exposição sobre brincadeiras populares feitos com materiais recicláveis e reutilizáveis em cada cidade visitada. Pretende-se atingir 3000 pessoas com a realização das 20 apresentações e exposições. CONTRAPARTIDA Este projeto pretende atingir contrapartidas distintas: apresentação teatral gratuita, com resgate e manutenção da cultura popular; exposição de brinquedos e brincadeiras populares com entrada franca, sem custo para o projeto, pois a exposição já é de produção da Cia. e acompanha o projeto. Além disso, temos parceria com Secretarias de Cultura, Educação, Promoção Social dos municípios para viabilizar uma parcela do público, além do público espontâneo. Utilizamos sempre aparelhos públicos com fácil acesso para as ações culturais promovidas pelo projeto, facilitando a comunicação das atividades com o público espontâneo. A presença de uma assessoria de imprensa garante a boa e eficaz divulgação. Procuramos utilizar espaços com o mínimo de recursos para atender portadores de necessidades especiais e terceira idade. O público do espetáculo, mesmo sendo destinado ao infantil, acaba recebendo adultos e muitos idosos, justamente pela contação de história e resgate da cultura popular. Por isso temos um público bem variado. • 20 apresentações gratuitas, atendendo cerca de 150 pessoas por apresentação – cerca de 3000 pessoas; • Utilização de espaços públicos e de fácil acesso; • 20 exposições “Reciclar e Brincar” – o público tem acesso no final de cada apresentação. |
      | **Arquivos para Download**            | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | **Links**                             | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | **Galeria de vídeo**                  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | **Galeria de fotos**                  | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | **Tags**                              | -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | Instagram                             | https://www.instagram.com/culturaviva/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Twitter/X                             | https://twitter.com/Culturaviva                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Facebook                              | https://web.facebook.com/cultura.viva                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | Vimeo                                 | https://vimeo.com/culturaviva                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | Youtube                               | https://www.youtube.com/@CulturaViva                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Linkedin                              | https://www.linkedin.com/in/cultura-viva-92a37521a/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | Spotify                               | https://open.spotify.com/user/23fmobc2l27nfhfr32nk7y6fq                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | Pinterest                             | https://br.pinterest.com/culturavivaoficial/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | **Publicado por**                     | Basis Tecnologia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | **Administrado por**                  | Basis Tecnologia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | **Subprojetos**                       | PETS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

  Cenário: 02. Visualizar Projeto - Baixar Arquivo
    Dado que o usuário acione a opção **Acessar** em um projeto
    E o sistema direciona o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário aciona algum **arquivo disponível para download**
    Então o sistema realiza o download do arquivo
    E o usuário permanece na **Visualização do Projeto**

  Cenário: 03. Visualizar Projeto - Acessar Links
    Dado que o usuário acione a opção **Acessar** em um projeto
    E o sistema direciona o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário aciona algum link na região **Links** do formulário de visualização
    Então o sistema redireciona o usuário para o link acionado conforme a [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)

  Cenário: 04. Visualizar Projeto - Reproduzir Vídeo
    Dado que o usuário acione a opção **Acessar** em um projeto
    E o sistema direciona o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário aciona algum vídeo na região **Galeria de vídeo** do formulário de visualização
    Então o sistema abre janela para a **reprodução do vídeo acionado** conforme a [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)

  Cenário: 05. Visualizar Projeto - Reproduzir Vídeo - Sair
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direciona o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona algum vídeo na região **Galeria de vídeo** do formulário de visualização
    E o sistema abre janela para a **reprodução do vídeo acionado** conforme a [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)
    Quando o usuário aciona a opção **Sair**
    Então o sistema **fecha** a janela de reprodução do vídeo
    E o usuário permanece na **Visualização do Projeto**

  Cenário: 06. Visualizar Projeto - Visualizar fotos
    Dado que o usuário acione a opção **Acessar** em um projeto
    E o sistema direciona o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário aciona alguma foto da **Galeria de fotos** do formulário de visualização
    Então o sistema abre janela para a **visualização da foto acionada** conforme a [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)

  Cenário: 07. Visualizar Projeto - Visualizar fotos - Sair
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direciona o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona alguma foto na região **Galeria de fotos** do formulário de visualização
    E o sistema abre janela para a **visualização da foto acionada** conforme a [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)
    Quando o usuário aciona a opção **Sair**
    Então o sistema **fecha** a janela de visualização de fotos
    E o usuário permanece na **Visualização do Projeto**

  Cenário: 08. Visualizar Projeto - Verificações disponíveis
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário aciona a opção **Incluir Verificação** no formulário de visualização
    Então o sistema exibe janela para **seleção da verificação** pretendida conforme a [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7)

  Cenário: 09. Visualizar Projeto - Verificações disponíveis - Filtrar
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona a opção **Incluir Verificação** no formulário de visualização
    Quando o usuário preenche o **campo de filtro**
    Então o sistema exibe a **Lista de Verificações** de acordo com o dado preenchido conforme a [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7)

  Cenário: 10. Visualizar Projeto - Verificações disponíveis - Filtro sem retorno
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona a opção **Incluir Verificação** no formulário de visualização
    Quando o usuário preenche o **campo de filtro**
    E o sistema **não** encontra nenhum registro para o dado preenchido
    Então o sistema exibe a [MSG-01](#/scenario/Mensagem_de_Interface_MINC_MAPAS_7.0_Mensagens_de_Interface/1)

  Cenário: 11. Visualizar Projeto - Incluir Verificação
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona a opção **Incluir Verificação** no formulário de visualização
    Quando o usuário seleciona uma das **verificações** disponíveis na lista
    Então o sistema **adiciona** a respectiva verificação no cadastro do projeto

  Cenário: 12. Visualizar Projeto - Remover Verificação - Sim
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona a opção **Remover** em alguma das **verificações** do cadastro do projeto
    E o sistema exibe a [MSG-02](#/scenario/Mensagem_de_Interface_MINC_MAPAS_7.0_Mensagens_de_Interface/2) com as opções **SIM** e **NÃO**
    Quando o usuário seleciona a opção **SIM**
    Então o sistema **remove** a respectiva verificação do projeto

  Cenário: 13. Visualizar Projeto - Remover Verificação - Não
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    E o usuário aciona a opção **Remover** em alguma das **verificações** do cadastro do projeto
    E o sistema exibe a [MSG-02](#/scenario/Mensagem_de_Interface_MINC_MAPAS_7.0_Mensagens_de_Interface/2) com as opções **SIM** e **NÃO**
    Quando o usuário seleciona a opção **NÃO**
    Então o sistema retorna para a **Visualização do Projeto**

  Cenário: 14. Visualizar Projeto - Compartilhar
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário aciona uma opção da área **Compartilhar** conforme a [RNG-08](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/8)
    Então o sistema **redireciona** o usuário para a **página de compartilhamento** da respectiva rede social acionada conforme [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)

  Cenário: 15. Visualizar Projeto - Visualizar perfil de publicador
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário **acessa o perfil** apresentado no <Campo>
      | Campo                                |
      | Publicado por                        |
    Então o sistema redireciona o usuário para a funcionalidade de **Visualizar Agente**

  Cenário: 16. Visualizar Projeto - Denúncia
    Dado que o sistema apresente a **Lista de Projetos**
    E o usuário acione a opção **Acessar** em um Projeto da lista
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário seleciona a opção **Denúncia**
    Então o sistema direciona o usuário para a funcionalidade: [**Denunciar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_004_Denunciar/00)

  Cenário: 17. Visualizar Projeto - Contato
    Dado que o sistema apresente a **Lista de Projetos**
    E o usuário acione a opção **Acessar** em um Projeto da lista
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário seleciona a opção **Contato**
    Então o sistema direciona o usuário para a funcionalidade: [**Contato Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_005_Contato/00)

  Cenário: 18. Visualizar Projeto - Editar
    Dado que o sistema apresente a **Lista de Projetos**
    E o usuário acione a opção **Acessar** em um Projeto da lista
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário seleciona a opção **Editar projeto**
    Então o sistema direciona o usuário para a funcionalidade: [**Editar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_006_Editar/00)

  Cenário: 19. Visualizar Projeto - Arquivar
    Dado que o sistema apresente a **Lista de Projetos**
    E o usuário acione a opção **Acessar** em um Projeto da lista
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário seleciona a opção **Arquivar**
    Então o sistema direciona o usuário para a funcionalidade: [**Arquivar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_007_Arquivar/00)

  Cenário: 20. Visualizar Projeto - Excluir
    Dado que o sistema apresente a **Lista de Projetos**
    E o usuário acione a opção **Acessar** em um Projeto da lista
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário seleciona a opção **Excluir**
    Então o sistema direciona o usuário para a funcionalidade: [**Excluir Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_008_Excluir/00)

  Cenário: 21. Visualizar Projeto - Visualizar perfil de administrador
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário **acessa um dos perfis** apresentados no <Campo>
      | Campo            |
      | Administrado por |
    Então o sistema redireciona o usuário para a funcionalidade de **Visualizar Agente**

  Cenário: 22. Visualizar Projeto - Visualizar subprojeto
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário **acessa o projeto** apresentado no <Campo>
      | Campo                                |
      | Subprojetos                          |
    Então o sistema redireciona o usuário para a funcionalidade de **Visualização** do respectivo projeto

  Cenário: 23. Visualizar Projeto - Visualizar macroprojeto
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário **acessa o projeto** apresentado no <Campo>
      | Campo                                |
      | PROJETO INTEGRANTE DE                |
    Então o sistema redireciona o usuário para a funcionalidade de **Visualização** do respectivo projeto

  Cenário: 24. Visualizar Projeto - Visualizar Oportunidade
    Dado que o usuário acione a opção **Acessar** em um Projeto
    E o sistema direcione o usuário para a funcionalidade: [**Visualizar Projeto**](#/scenario/01_Manter_Projetos_MINC_MAPAS_7.0_EPE01_003_Visualizar/00)
    Quando o usuário **acessa a oportunidade** apresentada no <Campo>
      | Campo                             |
      | Lista de oportunidades vinculadas |
    Então o sistema redireciona o usuário para a funcionalidade de **Visualização** da respectiva oportunidade

  Cenário: Protótipos
  ![Image](MINC_MAPAS_7.0_EPE01_003_Visualizar.png)
  ![Image](MINC_MAPAS_7.0_EPE01_003_Lista_Verificacoes.png)
  ![Image](MINC_MAPAS_7.0_EPE01_003_Janela_Visualizar_Midia.png)
