# language: pt
# encoding: utf-8

Funcionalidade: MINC_MAPAS_7.0_EPE01_010_Regras_de_Interface

  ---

  **COMO** usuário do sistema **MAPAS 7.0**

  **QUERO** definir as regras de interface

  **PARA** manter a integridade do sistema

  ---

  Cenário: 01. Listar Projetos
    Dado que o sistema esteja exibindo a **Lista de Projetos**
      | Campos            | Descrição                                         | Tipo do campo    | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                                                                                          |
      | Título            | Nome do Projeto                                   | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | ID                | Identificador do Projeto                          | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | TIPO              | Tipo do Projeto                                   | Label            | Texto        | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Descrição         | Descrição curta sobre o projeto                   | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | SELOS             | Certificações do projeto                          | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Título do projeto | Nome do projeto para consulta                     | Label            | Texto        | N/A     | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Status do projeto | Status em que se encontra o projeto para consulta | Checkbox         | Checkbox     | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |
      | Tipos de projetos | Tipo do projeto para consulta                     | Seleção múltipla | Domínio Fixo | -       | -       | -    | -        | -           | [RNG-02](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/2), [RNG-03](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/3), [RNG-04](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/4) e [RNG-09](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/9) |

  Cenário: 02. Cadastrar Projetos
    Dado que o sistema esteja exibindo o **Formulário de Cadastro de Projetos**
      | Campos                                      | Descrição                     | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                                        | Nome do Projeto               | Label         | Texto        | N/A     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Linguagem cultural                          | Linguagem cultural do projeto | Seleção única | Domínio fixo | -       | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |
      | Adicione uma Descrição curta para o Projeto | Descrição curta do projeto    | Label         | Texto        | 400     | -       | -    | -        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10) |

  Cenário: 03. Visualizar Projetos
    Dado que o sistema esteja exibindo o **Formulário de Visualização de Projetos**
      | Campos                 | Descrição                                                       | Tipo do campo    | Tipo do dado | Tamanho | Máscara         | Hint | Editável | Obrigatório | Regras                                                                 |
      | Imagem de capa         | Imagem da capa do projeto                                       | Arquivo          | Arquivo      | N/A     | -               | -    | S        | -           | -                                                                      |
      | Imagem de perfil       | Imagem do perfil do projeto                                     | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | -                                                                      |
      | Nome do Projeto        | Título do projeto                                               | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | TIPO                   | Tipo do projeto                                                 | Seleção única    | Domínio fixo | N/A     | -               | -    | N        | -           | -                                                                      |
      | ID                     | Identificador do projeto                                        | Label            | Alfanumérico | N/A     | -               | -    | N        | -           | -                                                                      |
      | PROJETO INTEGRANTE DE  | Projeto macro do projeto atual                                  | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Descrição curta        | Descrição resumida do projeto                                   | Label            | Texto        | 400     | -               | -    | N        | -           | -                                                                      |
      | Link do Projeto        | Endereço eletrônico de página web relacionada ao projeto        | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Nome da Oportunidade   | Nome das oportunidades vinculadas ao projeto                    | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Telefone(Público)      | Número de telefone que será exibido publicamente                | Label            | Texto        | N/A     | (xx) xxxxx-xxxx | -    | N        | -           | -                                                                      |
      | E-mail(Público)        | Endereço de e-mail que será exibido publicamente                | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Descrição Detalhada    | Descrição detalhada do projeto                                  | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Arquivos para Download | Arquivos disponibilizados para download relacionados ao projeto | Arquivo          | Arquivo      | 10mb    | -               | -    | N        | -           | -                                                                      |
      | Links                  | Links relevantes para o projeto                                 | Label            | Texto        | N/A     | -               | -    | N        | -           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Galeria de vídeo       | Galeria de vídeos relevantes para o projeto                     | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6) |
      | Galeria de fotos       | Galeria de imagens relevantes para o projeto                    | Arquivo          | Arquivo      | N/A     | -               | -    | N        | -           | [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6) |
      | Tags                   | Tags relacionadas ao projeto                                    | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Instagram              | Endereço de Instagram relacionao ao projeto                     | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Twitter/X              | Endereço de Twitter/X relacionao ao projeto                     | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Facebook               | Endereço de Facebook relacionao ao projeto                      | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Vimeo                  | Endereço de Vimeo relacionao ao projeto                         | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Youtube                | Endereço de canal no Youtube relacionao ao projeto              | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Linkedin               | Endereço de Linkedin relacionao ao projeto                      | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Spotify                | Endereço de Spotify relacionao ao projeto                       | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Pinterest              | Endereço de Pinterest relacionao ao projeto                     | Label            | Texto        | N/A     | -               | -    | N        | N           | [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5) |
      | Publicado por          | Publicador do projeto                                           | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Administrado por       | Administradores do projeto                                      | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Subprojetos            | Subprojetos cujo projeto atual seja um macro projeto            | Label            | Texto        | N/A     | -               | -    | N        | -           | -                                                                      |
      | Verificações           | Certificações do projeto                                        | Seleção múltipla | Domínio fixo | N/A     | -               | -    | S        | -           | [RNG-07](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/7) |

  Cenário: 04. Denunciar Projeto
    Dado que o sistema esteja exibindo o **Formulário de Denúncia de Projeto**
      | Campos                           | Descrição                                                | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                             | Nome do denunciante                                      | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | E-mail                           | E-mail do denunciante                                    | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-11](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/11) |
      | Tipo                             | Tipo da denúncia                                         | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                         | Mensagem de detalhamento da denúncia                     | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar denúncia de forma anônima | Possibilidade de anonimato ao enviar a denúncia          | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem        | Possibilidade de receber uma cópia do e-mail de denúncia | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 05. Contato de Projeto
    Dado que o sistema esteja exibindo o **Formulário de Contato de Projeto**
      | Campos                             | Descrição                                                                      | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                  |
      | Nome                               | Nome do remetente                                                              | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | E-mail                             | E-mail do remetente                                                            | Label         | Texto        | N/A     | -       | -    | S        | S           | [RNG-25](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/25) |
      | Tipo                               | Tipo da mensagem                                                               | Seleção única | Domínio fixo | -       | -       | -    | S        | S           | -                                                                       |
      | Mensagem                           | Mensagem de detalhamento do contato                                            | Label         | Texto        | N/A     | -       | -    | S        | S           | -                                                                       |
      | Enviar a mensagem de forma anônima | Possibilidade de anonimato ao enviar a mensagem                                | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Receber cópia da mensagem          | Possibilidade de receber uma cópia do e-mail de denúncia                       | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |
      | Enviar somente para o responsável  | Possibilidade de enviar a mensagem apenas para agente responsável pelo projeto | Checkbox      | Checkbox     | -       | -       | -    | S        | -           | -                                                                       |

  Cenário: 06. Editar Projetos
    Dado que o sistema esteja exibindo o **Formulário de Edição de Projetos**
      | Campos                              | Descrição                                                       | Tipo do campo    | Tipo do dado | Tamanho | Máscara            | Hint | Editável | Obrigatório | Regras                                                                                                                                                                                                                    |
      | Imagem de capa                      | Imagem da capa do projeto                                       | Arquivo          | Arquivo      | N/A     | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Imagem de perfil                    | Imagem do perfil do projeto                                     | Arquivo          | Arquivo      | N/A     | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20)                                                                          |
      | Nome do Projeto                     | Título do projeto                                               | Label            | Texto        | N/A     | -                  | -    | S        | S           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Tipo do projeto                     | Tipo do projeto                                                 | Seleção única    | Domínio fixo | N/A     | -                  | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Descrição curta                     | Descrição resumida do projeto                                   | Label            | Texto        | 400     | -                  | -    | S        | S           | -                                                                                                                                                                                                                         |
      | Link para página ou site do projeto | Endereço eletrônico de página web relacionada ao projeto        | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                                                                                                   |
      | Projeto vinculado à                 | Projeto macro relacionado ao projeto atual                      | Seleção única    | Domínio fixo | -       | -                  | -    | S        | N           | [RNG-21](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/21), [RNG-22](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/22)                                                                          |
      | Instagram                           | Endereço de Instagram relacionao ao projeto                     | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Twitter/X                           | Endereço de Twitter/X relacionao ao projeto                     | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Facebook                            | Endereço de Facebook relacionao ao projeto                      | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Vimeo                               | Endereço de Vimeo relacionao ao projeto                         | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Youtube                             | Endereço de canal no Youtube relacionao ao projeto              | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Linkedin                            | Endereço de Linkedin relacionao ao projeto                      | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Spotify                             | Endereço de Spotify relacionao ao projeto                       | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Pinterest                           | Endereço de Pinterest relacionao ao projeto                     | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Data inicial                        | Data de início do projeto                                       | Data e Hora      | Data e Hora  | 018     | 00/00/0000 - 00:00 | -    | S        | N           | [RNG-14](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/14)                                                                                                                                                   |
      | Data final                          | Data de término do projeto                                      | Data e Hora      | Data e Hora  | 018     | 00/00/0000 - 00:00 | -    | S        | N           | [RNG-14](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/14), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | E-mail Público                      | Endereço de e-mail que será exibido publicamente                | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-15](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/15), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | E-mail Privado                      | Endereço de e-mail privado, que não será exibido publicamente   | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-15](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/15), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone Público                    | Número de telefone que será exibido publicamente                | Label            | Texto        | N/A     | (xx) xxxxx-xxxx    | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone privado 1                  | Número de telefone privado, que não será exibido publicamente   | Label            | Texto        | N/A     | (xx) xxxxx-xxxx    | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Telefone privado 2                  | Número de telefone privado, que não será exibido publicamente   | Label            | Texto        | N/A     | (xx) xxxxx-xxxx    | -    | S        | N           | [RNG-16](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/16), [RNG-10](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/10)                                                                          |
      | Descrição                           | Descrição detalhada do projeto                                  | Label            | Texto        | N/A     | -                  | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Adicionar arquivo para download     | Arquivos disponibilizados para download relacionados ao projeto | Arquivo          | Arquivo      | 10mb    | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-18](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/18), [RNG-19](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/19) |
      | Adicionar links                     | Links relevantes para o projeto                                 | Label            | Texto        | N/A     | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-05](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/5)  |
      | Adicionar vídeos                    | Galeria de vídeos relevantes para o projeto                     | Arquivo          | Arquivo      | N/A     | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-17](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/17), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Adicionar fotos na galeria          | Galeria de imagens relevantes para o projeto                    | Arquivo          | Arquivo      | N/A     | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-20](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/20), [RNG-06](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/6)  |
      | Nome do agente                      | Nome de agente relacionado como administrador do projeto        | Seleção múltipla | Domínio fixo | -       | -                  | -    | S        | N           | [RNG-13](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/13), [RNG-23](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/23)                                                                          |
      | Nome da Tag                         | Tags relacionadas ao projeto                                    | Seleção múltipla | Texto        | N/A     | -                  | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do Grupo                       | Grupos relacionados ao projeto                                  | Seleção múltipla | Texto        | N/A     | -                  | -    | S        | N           | -                                                                                                                                                                                                                         |
      | Nome do agente                      | Nome de agente relacionado como publicador do projeto           | Seleção única    | Domínio fixo | -       | -                  | -    | S        | S           | [RNG-24](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/24)                                                                                                                                                   |

  Cenário: 07. Meus Projetos
    Dado que o sistema esteja exibindo a **Lista de Projetos Pessoais**
      | Campos         | Descrição                                   | Tipo do campo | Tipo do dado | Tamanho | Máscara | Hint | Editável | Obrigatório | Regras                                                                                                                                            |
      | Título         | Nome do Projeto                             | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-28](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/28) |
      | TIPO           | Tipo do Projeto                             | Label         | Texto        | -       | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-28](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/28) |
      | Palavras-chave | Palavra que faça parte do título do projeto | Label         | Texto        | N/A     | -       | -    | -        | -           | [RNG-27](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/27) e [RNG-28](#/scenario/Regras_de_Negócio_MINC_MAPAS_7.0_Regras_Negócio/28) |
